### ISSUE TITLE
Using MDL custom themes

### ISSUE THREAD

**Issue by dev357** [mebibou/mdl-selectfield#13]
The selectfield always uses the default theme of mdl(dark blue color for the underline and label. Is it possible to make it use the custom theme colors?

If so, perhaps have a mention of how in the readme?

**Comment by mebibou** [comment]
Hum good question, I personally do not use this library in any project anymore, so I won't be able to test it, but to be able to use the same colors as the mdl library, I needed to import the mdl-library itself as seen [here](https://github.com/mebibou/mdl-selectfield/blob/master/src/selectfield/selectfield.scss#L1)

If the scss file didn't have the imports and you would import it in your project, would it work? rather than include the script somewhere in your page

**Comment by dev357** [comment]
I am using mdl with react-mdl, which seems to be generating its own css files for some layout specific reasons(without any sass that i can see on the github page). But i guess i could just manually insert the correct colors into your selectfield.scss and make it work that way. Thanks.

**Comment by mebibou** [comment]
Glad you found a solution :)
