### ISSUE TITLE
Reset button does not reset <select> element

### ISSUE THREAD

**Issue by od3n** [mebibou/mdl-selectfield#9]

**Comment by mebibou** [comment]
Could you be more specific on what this reset button is?

**Comment by legendarydrew** [comment]
I think they mean a `<button type="reset"></button>"` or `<input type="reset">"`, which resets form fields to their initial values.

**Comment by od3n** [comment]
yes, thanks @legendarydrew

**Comment by mebibou** [comment]
@od3n fyi the `reset` event is only for `<form>` elements, i.e. when clicking on your `<input type="reset">` only the `<form>` will receive the event, and not the `<select>` element. So since this library only handles the `<select>` element, you can then propagate the `reset` event yourself.

You can have a look here: https://github.com/google/material-design-lite/pull/1569
